services:
  checkmk-dev:
    image: checkmk/check-mk-pro:${CMK_VERSION}
    hostname: checkmk-dev
    ports:
      - "8080:5000"
    environment:
      - CMK_PASSWORD=${CMK_PASSWORD}
      - TZ=${TZ}
    volumes:
      - checkmk-sites:/omd/sites
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./local
          target: /omd/sites/cmk/local
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"

volumes:
  checkmk-sites: